# Generated by Django 3.0.8 on 2020-07-18 08:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maids', '0002_maid_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maid',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='maid',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=None, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maid',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
